services:
  web:
    build:
      context: ./cartogram-web/
      dockerfile: Dockerfile
    image: gocartio/cartogram-web
    profiles: [web]
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    environment:
      - CARTOGRAM_DEBUG=TRUE
      - CARTOGRAM_DATABASE_URI=postgresql://cartogram:password@postgres/cartogram
    command: sh -c "pip install pytest && python web.py"
    ports:
      - "5001:5000"
    volumes:
      - ./cartogram-web/internal:/root/internal
      - ./cartogram-web/data:/root/data
      - ./data/userdata:/root/internal/static/userdata

  exp:
    build:
      context: ./cartogram-exp/
      dockerfile: Dockerfile
    image: gocartio/cartogram-web
    profiles: [exp]
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    environment:
      - CARTOGRAM_DEBUG=TRUE
      - CARTOGRAM_DATABASE_URI=postgresql://cartogram:password@postgres/cartogramexp
      - VITE_SERVER_PORT=5174
    command: sh -c "python -c \"import web; web.db.create_all()\" && python web.py"
    ports:
      - "5000:5000"
    volumes:
      - ./cartogram-exp/internal:/root/internal
      - ./cartogram-exp/data:/root/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=cartogramexp
      - POSTGRES_USER=cartogram
      - POSTGRES_PASSWORD=password
