name: Pull latest gocartio/cartogram-web image on host (go-cart.io)

on:
  # only when triggered manually, after we have tested it ourselves
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  pull-new-cartogram-web-image:
    runs-on: ubuntu-latest
    steps:
      - name: Update cartogram docker and web image on go-cart.io server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: cartogram
          key: ${{ secrets.SERVER_SSH_ACCESS_KEY }}
          script: |
            # Reset all changes before pull to prevent conflicts
            cd ~/cartogram-docker
            git fetch origin
            git reset --hard origin/main
            git pull origin main

            SHORT_SHA=$(git ls-tree HEAD cartogram-web | awk '{print $3}' | xargs git rev-parse --short)
            export TAG=":$SHORT_SHA"

            # Pull gocartio/cartogram-web:SHORT_SHA
            docker compose -f docker-compose.yml pull web
            docker compose -f docker-compose.yml up -d

            # Clean up old image
            docker image prune -a -f

            # Make sure the user in docker container has execute permissions
            docker exec cartogram-docker-web-1 chmod +x executable/cartogram
            CPP_VERSION=$(docker exec cartogram-docker-web-1 executable/cartogram --version)

            # Sanity checks
            echo "cartogram-web submodule SHA: $SHORT_SHA"
            echo "Tag: $TAG"

            # Capture the image name from docker inspect
            echo "Pulled image: $(docker inspect --format='{{.Config.Image}}' cartogram-docker-web-1)"
            echo "cartogram-cpp version: $CPP_VERSION"
